name: nfc_manager_ndef
description: A Flutter package that provides the abstraction of the NDEF features of the nfc_manager plugin.
version: 1.0.0-dev
repository: https://github.com/okadan/flutter-nfc-manager-ndef
publish_to: none # TODO: remove this line

environment:
  sdk: ^3.2.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ndef_record:
    git: https://github.com/okadan/dart-ndef-record
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager
      ref: v4.0.0

dev_dependencies:
  flutter_lints:
